# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/hotel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setIconSize(QtCore.QSize(36, 36))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.tabWidget.setMinimumSize(QtCore.QSize(800, 600))
        self.tabWidget.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 264, 43))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.TrainButton = QtWidgets.QCommandLinkButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.TrainButton.setFont(font)
        self.TrainButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.TrainButton.setStyleSheet("font-size:16px;")
        self.TrainButton.setObjectName("TrainButton")
        self.horizontalLayout.addWidget(self.TrainButton)
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(300, 40, 391, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(30, 240, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.radio_input = QtWidgets.QRadioButton(self.tab)
        self.radio_input.setGeometry(QtCore.QRect(70, 130, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radio_input.setFont(font)
        self.radio_input.setChecked(True)
        self.radio_input.setObjectName("radio_input")
        self.frame_input = QtWidgets.QFrame(self.tab)
        self.frame_input.setGeometry(QtCore.QRect(230, 150, 451, 61))
        self.frame_input.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_input.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_input.setObjectName("frame_input")
        self.input = QtWidgets.QLineEdit(self.frame_input)
        self.input.setGeometry(QtCore.QRect(10, 10, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input.setFont(font)
        self.input.setText("")
        self.input.setMaxLength(40)
        self.input.setObjectName("input")
        self.reset = QtWidgets.QPushButton(self.frame_input)
        self.reset.setEnabled(True)
        self.reset.setGeometry(QtCore.QRect(300, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.reset.setFont(font)
        self.reset.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/Reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reset.setIcon(icon1)
        self.reset.setObjectName("reset")
        self.analyse = QtWidgets.QPushButton(self.frame_input)
        self.analyse.setEnabled(False)
        self.analyse.setGeometry(QtCore.QRect(340, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.analyse.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/Analyse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.analyse.setIcon(icon2)
        self.analyse.setIconSize(QtCore.QSize(20, 20))
        self.analyse.setObjectName("analyse")
        self.radio_openfile = QtWidgets.QRadioButton(self.tab)
        self.radio_openfile.setGeometry(QtCore.QRect(70, 170, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radio_openfile.setFont(font)
        self.radio_openfile.setObjectName("radio_openfile")
        self.frame_openfile = QtWidgets.QFrame(self.tab)
        self.frame_openfile.setGeometry(QtCore.QRect(200, 130, 481, 101))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.frame_openfile.setFont(font)
        self.frame_openfile.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_openfile.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_openfile.setObjectName("frame_openfile")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_openfile)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 10, 451, 88))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(10, 0, 10, 0)
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.open_csv = QtWidgets.QCommandLinkButton(self.layoutWidget1)
        self.open_csv.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_csv.setStyleSheet("border:n\n"
"QCommandLinkButton:hover{\n"
"    border:1px solid;\n"
"}\n"
"")
        self.open_csv.setObjectName("open_csv")
        self.gridLayout.addWidget(self.open_csv, 0, 0, 1, 1)
        self.open_json = QtWidgets.QCommandLinkButton(self.layoutWidget1)
        self.open_json.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_json.setStyleSheet("border:none\n"
"QCommandLinkButton:hover{\n"
"    border:1px solid #ddd;\n"
"}")
        self.open_json.setObjectName("open_json")
        self.gridLayout.addWidget(self.open_json, 0, 1, 1, 1)
        self.open_sql = QtWidgets.QCommandLinkButton(self.layoutWidget1)
        self.open_sql.setEnabled(False)
        self.open_sql.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_sql.setStyleSheet("border:none\n"
"QCommandLinkButton:hover{\n"
"    border:1px solid #ddd;\n"
"}")
        self.open_sql.setObjectName("open_sql")
        self.gridLayout.addWidget(self.open_sql, 1, 0, 1, 1)
        self.open_txt = QtWidgets.QCommandLinkButton(self.layoutWidget1)
        self.open_txt.setEnabled(True)
        self.open_txt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.open_txt.setMouseTracking(False)
        self.open_txt.setStyleSheet("border:n\n"
"QCommandLinkButton:hover{\n"
"    border:1px solid #ddd;\n"
"}")
        self.open_txt.setObjectName("open_txt")
        self.gridLayout.addWidget(self.open_txt, 1, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(40, 130, 20, 101))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(350, 270, 411, 271))
        self.groupBox.setObjectName("groupBox")
        self.OutputBox = QtWidgets.QTextBrowser(self.groupBox)
        self.OutputBox.setGeometry(QtCore.QRect(20, 30, 361, 231))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.OutputBox.setFont(font)
        self.OutputBox.setStyleSheet("border:n")
        self.OutputBox.setObjectName("OutputBox")
        self.frame_inputResult = QtWidgets.QFrame(self.tab)
        self.frame_inputResult.setGeometry(QtCore.QRect(60, 300, 261, 161))
        self.frame_inputResult.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inputResult.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inputResult.setObjectName("frame_inputResult")
        self.rate = QtWidgets.QLabel(self.frame_inputResult)
        self.rate.setGeometry(QtCore.QRect(0, 130, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rate.setFont(font)
        self.rate.setObjectName("rate")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame_inputResult)
        self.graphicsView.setGeometry(QtCore.QRect(90, 30, 41, 41))
        self.graphicsView.setStyleSheet("background:url(:/img/Average.png) no-repeat;\n"
"border:n\n"
"")
        self.graphicsView.setObjectName("graphicsView")
        self.judge = QtWidgets.QLabel(self.frame_inputResult)
        self.judge.setGeometry(QtCore.QRect(0, 90, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.judge.setFont(font)
        self.judge.setObjectName("judge")
        self.frame_opResult = QtWidgets.QFrame(self.tab)
        self.frame_opResult.setGeometry(QtCore.QRect(80, 340, 191, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frame_opResult.setFont(font)
        self.frame_opResult.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_opResult.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_opResult.setObjectName("frame_opResult")
        self.line_2 = QtWidgets.QFrame(self.frame_opResult)
        self.line_2.setGeometry(QtCore.QRect(0, 20, 151, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.frame_opResult)
        self.line_3.setGeometry(QtCore.QRect(0, 58, 151, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.frame_opResult)
        self.line_4.setGeometry(QtCore.QRect(0, 92, 151, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_3 = QtWidgets.QLabel(self.frame_opResult)
        self.label_3.setGeometry(QtCore.QRect(1, 1, 96, 21))
        self.label_3.setObjectName("label_3")
        self.sum_show = QtWidgets.QLabel(self.frame_opResult)
        self.sum_show.setGeometry(QtCore.QRect(124, 1, 16, 21))
        self.sum_show.setObjectName("sum_show")
        self.label_6 = QtWidgets.QLabel(self.frame_opResult)
        self.label_6.setGeometry(QtCore.QRect(1, 37, 112, 21))
        self.label_6.setObjectName("label_6")
        self.pos_show = QtWidgets.QLabel(self.frame_opResult)
        self.pos_show.setGeometry(QtCore.QRect(124, 37, 16, 21))
        self.pos_show.setObjectName("pos_show")
        self.label_8 = QtWidgets.QLabel(self.frame_opResult)
        self.label_8.setGeometry(QtCore.QRect(1, 73, 112, 21))
        self.label_8.setObjectName("label_8")
        self.neg_show = QtWidgets.QLabel(self.frame_opResult)
        self.neg_show.setGeometry(QtCore.QRect(124, 73, 16, 21))
        self.neg_show.setObjectName("neg_show")
        self.label_10 = QtWidgets.QLabel(self.frame_opResult)
        self.label_10.setGeometry(QtCore.QRect(1, 109, 80, 21))
        self.label_10.setObjectName("label_10")
        self.aver_show = QtWidgets.QLabel(self.frame_opResult)
        self.aver_show.setGeometry(QtCore.QRect(90, 110, 51, 21))
        self.aver_show.setObjectName("aver_show")
        self.radio_net = QtWidgets.QRadioButton(self.tab)
        self.radio_net.setGeometry(QtCore.QRect(70, 207, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radio_net.setFont(font)
        self.radio_net.setObjectName("radio_net")
        self.frame_input.raise_()
        self.label_2.raise_()
        self.layoutWidget.raise_()
        self.progressBar.raise_()
        self.label_4.raise_()
        self.radio_input.raise_()
        self.radio_openfile.raise_()
        self.frame_openfile.raise_()
        self.line.raise_()
        self.groupBox.raise_()
        self.frame_opResult.raise_()
        self.radio_net.raise_()
        self.frame_inputResult.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(70, 40, 621, 451))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.testlayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.testlayout.setContentsMargins(0, 0, 0, 0)
        self.testlayout.setObjectName("testlayout")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "酒店评论情感分析系统"))
        self.label_2.setText(_translate("MainWindow", "步骤二：选择测试方式"))
        self.label.setText(_translate("MainWindow", "步骤一："))
        self.TrainButton.setText(_translate("MainWindow", "训练模型"))
        self.label_4.setText(_translate("MainWindow", "步骤三：查看测试结果"))
        self.radio_input.setText(_translate("MainWindow", "直接输入测试"))
        self.input.setPlaceholderText(_translate("MainWindow", "请在此输入测试评论"))
        self.analyse.setText(_translate("MainWindow", "分析"))
        self.radio_openfile.setText(_translate("MainWindow", "导入文件测试"))
        self.open_csv.setText(_translate("MainWindow", "打开.csv文件"))
        self.open_json.setText(_translate("MainWindow", "打开.json文件"))
        self.open_sql.setText(_translate("MainWindow", "打开.sql文件"))
        self.open_txt.setText(_translate("MainWindow", "打开.txt文件"))
        self.groupBox.setTitle(_translate("MainWindow", "Output"))
        self.rate.setText(_translate("MainWindow", "客户满意度约为：xx"))
        self.judge.setText(_translate("MainWindow", "该评价是一例..评价"))
        self.label_3.setText(_translate("MainWindow", "总测试用例："))
        self.sum_show.setText(_translate("MainWindow", "x"))
        self.label_6.setText(_translate("MainWindow", "正面评价数量："))
        self.pos_show.setText(_translate("MainWindow", "x"))
        self.label_8.setText(_translate("MainWindow", "负面评价数量："))
        self.neg_show.setText(_translate("MainWindow", "x"))
        self.label_10.setText(_translate("MainWindow", "综合指数："))
        self.aver_show.setText(_translate("MainWindow", "x"))
        self.radio_net.setText(_translate("MainWindow", "网络爬取测试"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "情感分析"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "图表与其他"))

from . import resource_rc
